name: Checks

on:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    name: black Format
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: black Format
        uses: psf/black@stable

  flake8-lint:
    runs-on: ubuntu-latest
    name: flake8 Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: flake8 Lint
        run: pip install flake8 & flake8

  pytest:
    runs-on: ubuntu-latest
    name: Run all Tests
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: pip install pytest & pytest
